### ISSUE TITLE
Write a Cron that backs up the DB to bunny everynight at 12

### ISSUE THREAD

**Issue by hkirat** [code100x/staging-ops#9]

**Comment by rishavvajpayee** [comment]
Hey can i take this up?

**Comment by rishavvajpayee** [comment]
https://github.com/code100x/staging-ops/pull/11

wrote a script with python.

**Comment by rishavvajpayee** [comment]
https://github.com/code100x/staging-ops/pull/11
python script for midnight cron uploads.

@hkirat

**Comment by isubhampadhi56** [comment]
#16 
Python application to Dump data from DB and write to Blob. This application also can be extended to support multiple DB and storage account

**Comment by imsamad** [comment]
plz have a look on PR #17 

wrote postgress backup setup with docker and cronjobs
